# -*- coding: utf-8 -*-
"""PyAnalytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17IqovUPhTzBpnggrWm2saT-c71C9i9b8

Atividade Prática - Esther de Oliveira

Desvendando APIs com Python e Dados de Saúde

Esta atividade tem como objetivo introduzir o conceito de APIs (Application Programming Interfaces) e demonstrar como podemos utilizar a linguagem Python para consumir dados reais de órgãos governamentais, focando na área da Saúde Pública.

Nesta etapa, importei as bibliotecas necessárias para cumprir os requisitos técnicos : requests para a comunicação com o servidor , pandas para a manipulação de DataFrames e matplotlib/seaborn para a plotagem dos gráficos.
"""

# Commented out IPython magic to ensure Python compatibility.
#Importar bibliotecaa
import requests
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# %matplotlib inline
sns.set_theme(style="whitegrid")
print("Ambiente preparado com sucesso!")

"""Para o desafio, utilizei o Portal da Transparência. A autenticação é feita através de uma chave (token) enviada no cabeçalho (headers) da requisição para identificar o usuário."""

# Chave de API
API_KEY = ""
# Endpoint do DataSUS para ocupação hospitalar
URL_DADOS = "https://apidadosabertos.saude.gov.br/assistencia-a-saude/registro-de-ocupacao-hospitalar-covid-19?limit=200"

headers = {
    "accept": "application/json",
    "chave-api-dados": API_KEY
}

response = requests.get(URL_DADOS, headers=headers, timeout=30)
print(f"Status da Conexão: {response.status_code} (200 significa sucesso!)")

"""Nesta etapa, o script realiza a busca dos dados, converte a resposta para o formato JSON e, em seguida, para um DataFrame do Pandas. Também realizei a limpeza e filtragem necessária para a análise."""

# Transformando em tabela
dados_json = response.json()
chave_raiz = list(dados_json.keys())[0]
df = pd.DataFrame(dados_json[chave_raiz])

# Busca dinâmica de colunas
col_estado = [c for c in df.columns if 'estado' in c.lower()][0]
col_valor = [c for c in df.columns if 'uti' in c.lower() or 'ocupacao' in c.lower()][0]

# Limpeza e Agrupamento
df[col_valor] = pd.to_numeric(df[col_valor], errors='coerce').fillna(0)
ranking = df.groupby(col_estado)[col_valor].sum().sort_values(ascending=False).reset_index()

print("Dados nacionais processados!")
display(ranking.head(10))

"""A última etapa do desafio consiste na plotagem dos gráficos para facilitar a interpretação dos dados extraídos."""

plt.figure(figsize=(14, 7))

# Criando o gráfico
grafico = sns.barplot(
    data=ranking.head(15),
    x=col_estado,
    y=col_valor,
    palette='viridis',
    hue=col_estado,     # Define as cores por estado
    legend=False,
    edgecolor="0.2"     # Contorno leve para destacar as colunas
)

# Customização de títulos e eixos
plt.title('Distribuição Nacional de Ocupação Hospitalar por Estado', fontsize=16, fontweight='bold', pad=20)
plt.xlabel('Estado (Unidade Federativa)', fontsize=12, labelpad=10)
plt.ylabel('Volume de Ocupação Registrada', fontsize=12, labelpad=10)

plt.xticks(rotation=45, ha='right', fontsize=10)

plt.tight_layout()
plt.show()

"""A realização desta atividade permitiu a aplicação prática de conceitos fundamentais de Ciência de Dados aplicados à Saúde Pública. Através do uso da linguagem Python e da biblioteca requests, foi possível estabelecer uma comunicação direta com a API de Dados Abertos do DataSUS, garantindo o acesso a informações atualizadas e oficiais."""